### ISSUE TITLE
Why pods are not being updated?

### ISSUE THREAD

**Issue by MrCoffey** [honestbee/drone-kubernetes#18]
I'm a new user of drone and I want to be able to deploy new code to my k8s cluster by using this plugin. So here is the thing, all the steps described in my pipeline runs ok, but it seems like the pod doesn't get updated after the deployment finish.

After some research, I found this PR https://github.com/honestbee/drone-kubernetes/pull/17, then what I did was to add `PLUGIN_FORCE: true` to my drone.yml manifesto, but pods still not being updated.

I am using the same tag in my deployment manifesto and in my drone manifesto.

There is something I am missing here? Thank you in advance.

**Comment by MacTynow** [comment]
@MrCoffey did you try running the update manually ? ```kubectl -n namespace set image deployment/your-deployment container=image:tag```

**Comment by MrCoffey** [comment]
Hi @MacTynow, the update command works only if the image tag is different from the current pod definition. In order to update the image is necessary to use a dynamic value in the drone pipeline manifesto. Drone.io provides `DRONE_COMMIT` variable, so in summary, using it as my image tag solves the issue. Thank you for helping me find a solution.
