### ISSUE TITLE
[Doc] Image tag from SHA is probably wrong

### ISSUE THREAD

**Issue by yonatane** [honestbee/drone-kubernetes#4]
Thanks for the plugin!
The image tag to be deployed (and published to a registry) should probably be the first 8 characters of the commit SHA:
`tag: ${DRONE_COMMIT_SHA:0:8}`
Instead of
`tag: ${DRONE_COMMIT_SHA:8}`
which is a substring starting from index 8.

**Comment by MacTynow** [comment]
@yonatane it still works but you're right... the idea is to get a short tag. I will change that. Thanks.
