### ISSUE TITLE
[Doc] Image tag from SHA should explicitly be a string

### ISSUE THREAD

**Issue by yonatane** [honestbee/drone-kubernetes#5]
Just today I ran into the problem of not wrapping `${DRONE_COMMIT_SHA:0:8}` with double quotes. A certain commit SHA was considered a number and it failed the deployment.

I suggest editing the docs replacing all occurrences of:`tag: ${DRONE_COMMIT_SHA:0:8}` with `tag: "${DRONE_COMMIT_SHA:0:8}"`.

**Comment by MacTynow** [comment]
Hi, thanks for the issue. I will remove mentions to `DRONE_COMMIT_SHA` as I have in the plugin index documentation (see [PR]( https://github.com/drone/drone-plugin-index/pull/36)). It's the second time an issue is opened about this particular tag and I think it is inducing people in error.
